In [213]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import MultinomialNB, ComplementNB, GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix, ConfusionMatrixDisplay

In [214]:
train_df = pd.read_csv("./train.csv")
test_df = pd.read_csv("./test.csv")

train_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [215]:
train_df['Age'] = train_df['Age'].fillna(train_df['Age'].median())

train_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [216]:
test_df['Age'] = test_df['Age'].fillna(test_df['Age'].median())
test_df.isna().sum()

test1 = test_df[["Pclass", "Age", "SibSp", "Parch"]].values

test1

array([[ 3. , 34.5,  0. ,  0. ],
       [ 3. , 47. ,  1. ,  0. ],
       [ 2. , 62. ,  0. ,  0. ],
       ...,
       [ 3. , 38.5,  0. ,  0. ],
       [ 3. , 27. ,  0. ,  0. ],
       [ 3. , 27. ,  1. ,  1. ]])

In [217]:
# converting the training data into inputs and outputs

x = train_df[["Pclass", "Age", "SibSp", "Parch"]].values
y = train_df[["Survived"]].values

x

array([[ 3., 22.,  1.,  0.],
       [ 1., 38.,  1.,  0.],
       [ 3., 26.,  0.,  0.],
       ...,
       [ 3., 28.,  1.,  2.],
       [ 1., 26.,  0.,  0.],
       [ 3., 32.,  0.,  0.]])

In [252]:
# splitting the training data to run the model for accuracy checking

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 42)

y_train

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
    

In [253]:
# training the machine using mulitple models and checking the accuracy scores to decide which model suits best

models = [MultinomialNB(), ComplementNB(), GaussianNB(), KNeighborsClassifier(n_neighbors = 5), SVC()]

for i in models:
    model = i
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    score = accuracy_score(y_test, y_pred)
    print("%.3f" % score, end="\n")

0.581
0.648
0.721
0.693
0.609


/home/codester/.local/lib/python3.8/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/codester/.local/lib/python3.8/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/codester/.local/lib/python3.8/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/codester/.local/lib/python3.8/site-packages/sklearn/neighbors/_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please 

In [259]:
# Decided to take Gaussian Naive Bayes model based on the above result to run the test data.

model = models[2]

model.fit(x, y)

pred = model.predict(test1)

pred

prediction = pd.DataFrame({"PassengerId": test_df["PassengerId"], "Survived": pred})

prediction

/home/codester/.local/lib/python3.8/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


PassengerId  Survived
0            892         0
1            893         0
2            894         1
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [260]:
submission = prediction.to_csv('/home/codester/Desktop/submission.csv', index = False)